microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/makepayment
        
        
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookorder
